addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install: go get -v github.com/spf13/hugo
script:
- hugo
notifications:
  email:
    on_faliure: always
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa
  - provider: script
    skip_cleanup: true
    script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/batmanslittlebird/
    on:
      branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_60e430c612c4_key -iv $encrypted_60e430c612c4_iv
  -in deploy_rsa.enc -out deploy.rsa -d
