baseurl = "http://batmanslittlebird.com/"
googleAnalytics = "UA-27993941-7"
languageCode = "en-us"
title = "Batman's Little Bird"
theme = "blb"

[params]
    coverart = "http://batmanslittlebird.com/coverart-temporary.jpg"
    subtitle = "A podcast about Dick"
    summary = "A podcast dedicated to the boy wonder, Dick Grayson where we talk about his history, and go through every comic he appears in"

[author]
  name = "Eric & Russell"

[[params.category]]
name="Arts"
subcategory="Visual Arts"

[[params.category]]
name="Comedy"

[[params.category]]
name="Games &amp; Hobbies"
subcategory="Hobbies"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -100
