baseurl = "http://batmanslittlebird.com/"
googleAnalytics = "UA-27993941-7"
languageCode = "en-us"
title = "Batman's Little Bird"
theme = "blb"
copyright = "Copyright 2016-7 Russell Hay &amp; Eric Fontenot"

[params]
    coverart = "/images/coverart.jpg"
    bannerart = "/images/coverart-small.jpg"
    subtitle = "A podcast about Dick"
    summary = "A podcast dedicated to the boy wonder, Dick Grayson where we talk about his history, and go through every comic he appears in"

[author]
  name = "Eric &amp; Russell"

[[params.category]]
name="Arts"
subcategory="Visual Arts"

[[params.category]]
name="Comedy"

[[params.category]]
name="Games &amp; Hobbies"
subcategory="Hobbies"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -100
