baseurl = "http://batmanslittlebird.com/"
googleAnalytics = "UA-27993941-7"
languageCode = "en-us"
title = "Batman's Little Bird"
theme = "blb"

[author]
  name = "Eric & Russell"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -100
